version: "3"

services:
  terra-validator:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /validator.toml
      --engine-signer ${VALIDATOR_ADDRESS}
      --nat extip:${IP_ADDRESS}
    user: root
    volumes:
      - ./validator.toml:/validator.toml:ro
      - ./terra-chain-spec:/chain-config:ro
      - chain-data:/root/.local/share/io.parity.ethereum/
      - ./key/validator.json:/root/.local/share/io.parity.ethereum/keys/${NETWORK}/validator.json:ro
      - ./key/validator.pwd:/key/validator.pwd:ro
    ports:
      - 30303:30303
      - 30303:30303/udp
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  chain-data:
