[parity]
chain = "/chain-config/chain.json"
auto_update = "critical"

[mining]
# Tx rate limiting for user
tx_queue_size = 1000
tx_queue_mem_limit = 512
tx_queue_per_sender = 100
tx_queue_strategy = "gas_price"
tx_queue_no_unfamiliar_locals = true
tx_time_limit = 5000 # 5 seconds

[footprint]
pruning = "archive"
cache_size = 128 # MB
pruning_memory = 32 # MB

[network]
discovery = true
reserved_peers = "/chain-config/bootnodes.txt"

[rpc]
port = 8545
interface = "0.0.0.0"
processing_threads = 4
cors = ["all"]
apis = ["safe"]
hosts = ["all"]

[websockets]
port = 8546
interface = "0.0.0.0"
max_connections = 1000
origins = ["all"]
hosts = ["all"]
apis = ["safe"]

[secretstore]
disable = true

[ui]
disable = true
